### ISSUE TITLE
Windows Phone Sample is not working 

### ISSUE THREAD

**Issue by khushalpatel1981** [IdentityServer/Thinktecture.IdentityServer3.Samples#70]
It's always saying "User cancelled authentication" when clicked on any button given on the screen

**Comment by brockallen** [comment]
In which environment? Also, what did the IdentityServer logs say?

**Comment by khushalpatel1981** [comment]
Nothing logs in the trace.log file, but when running clients project it is  logging events in the file.
Environment: Windows 10 Technical Preview, Visual Studio 2013
![bug](https://cloud.githubusercontent.com/assets/9281088/6015214/bfa7d314-ab97-11e4-9a71-3ab58c321dbc.PNG)

**Comment by brockallen** [comment]
That looks like an emulator, yes? If so, then it sounds like the emulator isn't even hitting the network -- that's what you need to debug. Also, we've not tested on windows 10 technical preview, so it's not something we can support right now.

**Comment by khushalpatel1981** [comment]
Yes, emulator is hitting the network and IdentityServer also but don't know why it is keep cancelling... may be some environmental issue, i will debug this on the real device and with a test server once i finish. I will update you in any case...

**Comment by khushalpatel1981** [comment]
Yes @brockallen you are right its working with the real device thanks for the help :)

**Comment by claq2** [comment]
The problem is that the phone emulator doesn't trust the localhost cert. You can put the cert on a web server and open it on the phone. This gives you the choice to install it, which seems to add it to the root CAs. Details are in this [blog post](http://blog.davidchristiansen.com/2014/12/self-signed-certificates-windows-apps-development/).
Running the SelfHost project I now get the IdentityServer3 UI, but it doesn't recognize the client. I'm guessing because the phone project is sending "implicitclient" but there's no such client defined in _sharedConfiguration\Clients.cs, but that's a different issue.
